spec/actions_manager_spec.coffee, src/actions_manager.coffee
Tackles two minor issues of `ActionManager`:
1. Allows `ActionManager` to receive more than one actions of `session` category without throwing. It skips consuming the action if there is a defined `Session`.
> Not part of this PR anymore
2. Currently, `ActionManager` expects the first action to be of a `session` category in order to `create` or `connect` a session and then consume the rest of actions. Otherwise, a `sendPageView` is reported. Because that is not always the case, a fix is provided to force `ActionManager` consume first actions of `session` category.
=> Allow ActionManager to receive multiple session category actions without throwing

spec/xdomain_engine_spec.coffee, src/session_engines/xdomain_engine.coffee
Currently, if the server respond after the socket timeout, then an exception is thrown because the promise is already fulfilled.
=> Resolve promise only once at XDomainEngine._onSocketMessage

Dockerfile, README.md, docker-compose.yml
To be used for development purposes, allowing the platform development dependencies (eg. node, npm) to point to the exact versions used when building the for production.
Any changes made to the code locally will be reflected inside the container.
Usage:
Run the tests
```shell
docker-compose run builder npm test
```
Build
```shell
docker-compose run builder grunt build
```
Watch
```shell
docker-compose run builder grunt watch
```
Start a shell
```shell
docker-compose run builder bash
```
=> Use Docker for development

src/loader.coffee
There are cases that iframe breaks the layout of a site.
Use `visibility: hidden;` instead of `display: none;` because Firefox currently does have an issue with `display:none;`
see: [stackoverflow/javascript-problem-with-iframe-thats-hidden-before-loaded/2786429#2786429](http://stackoverflow.com/questions/2730046/javascript-problem-with-iframe-thats-hidden-before-loaded/2786429#2786429)
=> Make iframe properly invisible

spec/plugins/order_stash_spec.coffee, src/plugins/order_stash.coffee
There are cases that a shop reports an order_id that makes no sense.
e.g null as string or empty string
*The purpose of this PR is to disable rendering the plugin if order_id is invalid.*
=> Handle invalid order_id in order_stash plugin

src/plugins/order_stash.coffee
Currently when analytics ecommerce tracking script is placed in head tag, order_stash plugin crashes randomly, depending on time is being loaded.
*We should be sure that `body` exists before order_stash is rendered.*
=> Render order_stash plugin on DOM ready

config/settings/default.yml
There are websites that when trying to extract the analytics session through the XDomainEngine are failing due to the 1sec timeout that is currently the default setting.
An increase to the `xdomain_session_timeout` will not affect the website's performance, nor other analytics actions (pageview etc).
=> Increase default xdomain_session_timeout to 5s

src/plugins/order_stash.coffee
When clicking on why or save the order, the `parent window` of the
plugin iframe is null. However the `window` property is being used
numerous times in previous methods and it is not null!
Also it seems to be a time sensitive issue. If you set a breakpoint,
then the `window` will be properly set.
A possible 'fix' is not to request the `window.parent.document` every 
time it is required, but instead store it in a variable on the order_stash constructor.
=> Store the window parent document in a variable

src/plugins/order_stash.coffee
Several shops use the `!important` declaration in CSS rules related to `color` or `font-size`, which cause rendering issues to the `order_stash` plugin.
This PR provides a fix for some cases, but there's a more general question that needs to be answered here: should we add `!important` declarations to more or even **all** our `color`, `font-size` CSS rules? Moreover, should we go about doing this to *all* our id-targeting CSS rules? 
This seems a bit kludgy but it's an one-off solution; otherwise we will continue to add such declarations every time we find some rendering issue.
=> Fix for rendering issues in order_stash plugin

config/settings/default.yml, spec/session_spec.coffee, spec/settings_spec.coffee, spec/xdomain_engine_spec.coffee, src/session.coffee, src/session_engines/xdomain_engine.coffee, src/settings.coffee.sample
This PR has to do with SkroutzAnalytics Multitenancy.
We need to run one instance of SkroutzAnalytics to serve multiple tenants/applications of Skroutz (skroutz.gr, alve.com, scrooge.co.uk)
=> Pass flavor/application_name on session create

src/plugins/order_stash.coffee
=> Set letter-spacing to zero in order_stash_plugin

spec/plugins/order_stash_spec.coffee, src/plugins/order_stash.coffee
There were 2 issues here:
1. 'transitionend' event was firing multiple times, actually for each
property transitioned("padding-right", "background-color", "background-position-x")
2. 'transitionend' event was working by coincidence, we are using CSS
animations to show/hide order_stash widget, but also we are using CSS
transitions on hover for order_stash button, so that was triggering a
transitionend event.
=> Attach 'animationend' event instead of 'transitionend' on click save button

config/settings/default.yml, spec/settings_spec.coffee
The name of the cookie is too generic, increasing the chance of
conflicts with other services.
The first party cookie expiration, under some cases, might get out
of sync with the third party cookies.
=> Modify the name and expiration of the first party cookie

src/plugins/order_stash.coffee
Explicitly set `font-weight` to sa-order-stash-plugin to `normal`, as it could be overridden by the host's style.
=> Set font-weight to normal in sa-order-stash-plugin

spec/plugins/badge_spec.coffee, src/plugins/badge.coffee
Specs:
```
Badge
floating
show/hide onscroll
when hide_on_scroll set to true
on small screen
✔ hides floating badge on scroll down
✔ shows floating badge on scroll up
when scoll horizontally
✔ does not change badge visibility
on big screen
✔ does not change badge visibility
when hide_on_scroll set to false
on small screen
✔ does not change badge visibility
on big screen
✔ does not change badge visibility
```
=> Toggle floating badge visibility onscroll

spec/session_spec.coffee, src/session.coffee
Only one session connect is allowed per analytics initialization.
=> Handle multiple session connects

config/settings/default.yml, spec/actions_manager_spec.coffee, spec/settings_spec.coffee, src/actions_manager.coffee, src/settings.coffee.sample
We use referer (misspelling of referrer) as param key for
compatibility with our backend.
Check: https://en.wikipedia.org/wiki/HTTP_referer
=> Append referrer url when parsing actions

spec/actions_manager_spec.coffee, src/actions_manager.coffee
Example Usage:
```js
sa('yogurt', 'productClick', '{\"product_id\":17970717}', function(url) {
window.location.replace(url)
}, 'https://www.shop.com/products/1');
```
The reason for this change is that redirecting from analytics.js does not
respect the meta referrer tag (actually it has something to do with FIF
technique).
=> Add functionality for custom redirect callback on productClick

src/loader.coffee
We found a case were a library [FrDH/jQuery.mmenu](https://github.com/FrDH/jQuery.mmenu) wipes the contents of our (friendly) iframe.
This library uses `$.wrapAll`, the problem with `$.wrapAll` is that it completely wipes the contents of any local iframe.
Actually the plugin does something [like](https://github.com/FrDH/jQuery.mmenu/blob/v6.1.8/src/core/offcanvas/jquery.mmenu.offcanvas.ts#L457):
```js
$("body > div").wrapAll( '<div />' ).parent();
```
So we try to append our iframe to body(if it's available) to avoid appending it inside another element and then having it wiped by [FrDH/jQuery.mmenu](https://github.com/FrDH/jQuery.mmenu).
=> Append (friendly) iframe to body if possible

config/settings/default.yml, spec/session_spec.coffee, spec/settings_spec.coffee, spec/xdomain_engine_spec.coffee, src/session.coffee, src/session_engines/xdomain_engine.coffee, src/settings.coffee.sample
analytics.js will pass additional metadata to the backend on session create via url parameters, provided by the base Application([skroutz](https://skroutz.gr), [alve](https://alve.com), [scrooge](https://scrooge.co.uk)).
The backend will be responsible to set and retrieve these data through 3rd party cookies.
**Note:**
*Additional metadata(as the rest of the params) should be url safe.*
*(This is already being handled by the base application)*
=> Pass metadata on session create

config/settings/default.yml, spec/actions_manager_spec.coffee, spec/session_spec.coffee, spec/settings_spec.coffee, spec/xdomain_engine_spec.coffee, src/session.coffee, src/session_engines/xdomain_engine.coffee, src/settings.coffee.sample
Avoid sending yogurt user id to Skroutz Analytics backend, for GDPR compliance reasons.
=> Don't send yogurt user id on session creation

config/settings/default.yml, spec/session_spec.coffee, spec/settings_spec.coffee, spec/xdomain_engine_spec.coffee, src/session.coffee, src/session_engines/xdomain_engine.coffee, src/settings.coffee.sample
Avoid sending yogurt_session to Skroutz Analytics backend, for GDPR compliance reasons.
=> Don't send yogurt session on session creation

tasks/wrappers/analytics/intro.js
This fixes a problem with Same-origin security policy when analytics is loaded inside another iframe.
The error:
```
DOMException: Blocked a frame with origin "http://www.<domain>.com" from accessing a cross-origin frame
```
Fixes: #44
=> Set global object to the parent of the current frame when inside a FIF

config/settings/development.yml.sample, config/settings/testing.yml.sample, spec/settings_spec.coffee, src/analytics.coffee, src/runnable.coffee, src/settings.coffee.sample, tasks/wrappers/analytics/outro.js
Since last week we have a conflict with Google Analytics and our namespace 'sa'.
see: [Google issues#116182847](https://issuetracker.google.com/issues/116182847)
With this change we will support **custom command queue function**(`sa()`) specified by the developer.
------------------------------
We should update also our documentation for Skroutz and Alve.
[Skroutz Analytics Tracking Script](https://developer.skroutz.gr/analytics/#step-1-integrate-the-analytics-tracking-script)
```html
<script type="text/javascript">
(function(a,b,c,d,e,f,g){a['SkroutzAnalyticsObject']=e;a[e]= a[e] || function(){
(a[e].q = a[e].q || []).push(arguments);};
f=b.createElement(c);f.async=true;
f.src=d;g=b.getElementsByTagName(c)[0];g.parentNode.insertBefore(f,g); …
```
=> Analytics Global Object

Gruntfile.coffee, spec/actions_manager_spec.coffee, spec/settings_spec.coffee, src/actions_manager.coffee, src/settings.coffee.sample, src/validator.coffee
Analytics Tracking Script will:
1. Make sure that the payload given to `addOrder` or `addItem` commands is a valid JSON before reporting them
1. Make sure `addOrder` has been supplied with a non-empty `order_id` field before reporting it
1. Make sure `addItem` has been supplied with non-empty `order_id` and `product_id` fields before reporting it
1. Log appropriate validation errors to console whenever the above constraints are not met
Also, Analytics Tracking Script will:
* Accept (unstringified) Object as payload. `JSON.stringify(...)` is not needed anymore.
------------
Documentation Update: [skroutz/developer.skroutz.gr/pull/93](https://github.com/skroutz/developer.skroutz.gr/pull/93)
=> Add presence validations for unique identifiers reported from shops (OO)

config/settings/default.yml, spec/settings_spec.coffee
Turns out a cookie lifetime duration of just 7 days was unnecessarily too short.
Changing it to 30 days, same as with the _Full_ cookie policy.
=> Extend Duration of Basic Cookies to 30 days

spec/plugins/partner_sku_reviews_spec.coffee, src/plugins/partner_sku_reviews.coffee, translations/alve.yml, translations/scrooge.yml, translations/skroutz.yml
We want to display if a review came from a verified purchase. The following screenshot is displayed on our partners' reviews page.
=> Add purchased verification mark for parter sku reviews

spec/plugins_manager_spec.coffee, src/plugins_manager.coffee
This reverts commit bec5e687516524336482a8b755d9284b0446749a.
=> Revert "Skip loading plugins temporarily"
